spring.application.name=API-Gateway
server.port = 8081

jwt.secret = Hey Shivani, I think I'm in love with you, What do you think? Nothing stupid
jwt.accessTokenExpirationInSec = 86400
jwt.refreshTokenExpirationInSec = 432000

spring.data.redis.host = localhost
spring.data.redis.port = 6379