spring.application.name=API-Gateway
server.port = 8081

jwt.secret = 8P6aLrQbiUxgakQsHhhejZdYZd50pqs1w9A7kbNxzK8
jwt.accessTokenExpirationInSec = 86400
jwt.refreshTokenExpirationInSec = 432000

spring.data.redis.host = localhost
spring.data.redis.port = 6379

gateway.routes[0].path = /feedback/**
gateway.routes[0].service = feedback-service

gateway.routes[1].path = /chat/**
gateway.routes[1].service = chat-service

gateway.routes[2].path = /event/**
gateway.routes[2].service = event-service
